-- AfterLoss Initial Database Schema
-- Issue #111: Create Supabase database schema and migrations
--
-- Architecture: Anonymous-first (user_id nullable on cases).
-- Users start without an account; localStorage holds progress.
-- Optional Supabase Auth account enables cross-device sync.

-- Enable moddatetime extension for automatic updated_at triggers
CREATE EXTENSION IF NOT EXISTS moddatetime WITH SCHEMA extensions;

-- =============================================================================
-- TABLE: state_probate_rules
-- Public reference data — probate rules for all 50 states + DC.
-- Powers programmatic SEO pages and personalized checklists.
-- =============================================================================
CREATE TABLE state_probate_rules (
  state_code TEXT PRIMARY KEY CHECK (char_length(state_code) = 2),
  state_name TEXT NOT NULL,
  probate_threshold NUMERIC,
  small_estate_affidavit_limit NUMERIC,
  simplified_probate_available BOOLEAN NOT NULL DEFAULT false,
  filing_deadline_days INTEGER,
  probate_court_website_url TEXT,
  required_documents JSONB DEFAULT '[]'::jsonb,
  estimated_timeline_months INTEGER,
  filing_fees_min NUMERIC,
  filing_fees_max NUMERIC,
  data_verified BOOLEAN NOT NULL DEFAULT false,
  source_url TEXT,
  last_verified_date TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- =============================================================================
-- TABLE: checklist_templates
-- Master checklist of all steps, organized by timeline category.
-- Public reference data — same for all users (state-filtered at query time).
-- =============================================================================
CREATE TABLE checklist_templates (
  step_id TEXT PRIMARY KEY,
  category TEXT NOT NULL CHECK (category IN ('immediate', 'first_week', 'first_month', 'first_quarter', 'first_year')),
  title TEXT NOT NULL,
  description TEXT,
  state_specific BOOLEAN NOT NULL DEFAULT false,
  applicable_states TEXT[] DEFAULT '{}',
  estimated_time_minutes INTEGER,
  required_documents TEXT[] DEFAULT '{}',
  deadline_rule TEXT,
  sort_order INTEGER NOT NULL DEFAULT 0
);

-- =============================================================================
-- TABLE: subscription_templates
-- Pre-written cancellation templates for common services.
-- Public reference data.
-- =============================================================================
CREATE TABLE subscription_templates (
  id SERIAL PRIMARY KEY,
  service_name TEXT NOT NULL,
  category TEXT NOT NULL CHECK (category IN ('streaming', 'utility', 'insurance', 'membership', 'financial', 'social_media', 'email', 'cloud_storage')),
  cancellation_method TEXT NOT NULL CHECK (cancellation_method IN ('online', 'phone', 'mail', 'email')),
  cancellation_contact TEXT,
  template_text TEXT,
  required_documents TEXT[] DEFAULT '{}'
);

-- =============================================================================
-- TABLE: cases
-- A case represents one death/estate settlement process.
-- user_id is NULLABLE to support anonymous-first architecture.
-- =============================================================================
CREATE TABLE cases (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  state TEXT REFERENCES state_probate_rules(state_code),
  date_of_death DATE,
  relationship_to_deceased TEXT CHECK (relationship_to_deceased IN ('spouse', 'child', 'sibling', 'parent', 'other')),
  estate_complexity TEXT CHECK (estate_complexity IN ('simple', 'moderate', 'complex')),
  deceased_name TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- =============================================================================
-- TABLE: case_checklist_items
-- Per-case progress on each checklist step.
-- =============================================================================
CREATE TABLE case_checklist_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  case_id UUID NOT NULL REFERENCES cases(id) ON DELETE CASCADE,
  template_step_id TEXT NOT NULL REFERENCES checklist_templates(step_id),
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'in_progress', 'completed', 'skipped')),
  completed_at TIMESTAMPTZ,
  notes TEXT,
  deadline_date DATE
);

-- =============================================================================
-- TABLE: generated_documents
-- Documents generated by Claude API for a specific case.
-- =============================================================================
CREATE TABLE generated_documents (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  case_id UUID NOT NULL REFERENCES cases(id) ON DELETE CASCADE,
  document_type TEXT NOT NULL,
  template_name TEXT,
  generated_content TEXT NOT NULL,
  pdf_storage_path TEXT,
  generated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- =============================================================================
-- TABLE: affiliate_partners
-- Affiliate partner directory for contextual recommendations.
-- =============================================================================
CREATE TABLE affiliate_partners (
  id SERIAL PRIMARY KEY,
  partner_name TEXT NOT NULL,
  category TEXT NOT NULL,
  url TEXT NOT NULL,
  description TEXT,
  commission_type TEXT,
  display_context TEXT[] DEFAULT '{}'
);

-- =============================================================================
-- TABLE: affiliate_clicks
-- Tracks affiliate link clicks for revenue analysis.
-- case_id nullable (anonymous users can click).
-- =============================================================================
CREATE TABLE affiliate_clicks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  case_id UUID REFERENCES cases(id) ON DELETE SET NULL,
  partner_id INTEGER NOT NULL REFERENCES affiliate_partners(id),
  checklist_step_id TEXT,
  clicked_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- =============================================================================
-- TABLE: deadline_reminders
-- Email reminders for upcoming deadlines (requires account).
-- =============================================================================
CREATE TABLE deadline_reminders (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  case_id UUID NOT NULL REFERENCES cases(id) ON DELETE CASCADE,
  checklist_item_id UUID NOT NULL REFERENCES case_checklist_items(id) ON DELETE CASCADE,
  reminder_date DATE NOT NULL,
  sent_at TIMESTAMPTZ
);

-- =============================================================================
-- INDEXES
-- =============================================================================
CREATE INDEX idx_cases_user_id ON cases(user_id);
CREATE INDEX idx_case_checklist_items_case_id ON case_checklist_items(case_id);
CREATE INDEX idx_deadline_reminders_case_id ON deadline_reminders(case_id);
CREATE INDEX idx_deadline_reminders_reminder_date ON deadline_reminders(reminder_date);
CREATE INDEX idx_affiliate_clicks_partner_id ON affiliate_clicks(partner_id);

-- =============================================================================
-- UPDATED_AT TRIGGERS (moddatetime)
-- =============================================================================
CREATE TRIGGER handle_updated_at_state_probate_rules
  BEFORE UPDATE ON state_probate_rules
  FOR EACH ROW
  EXECUTE FUNCTION extensions.moddatetime(updated_at);

CREATE TRIGGER handle_updated_at_cases
  BEFORE UPDATE ON cases
  FOR EACH ROW
  EXECUTE FUNCTION extensions.moddatetime(updated_at);

-- =============================================================================
-- ROW LEVEL SECURITY
-- =============================================================================

-- state_probate_rules: public read-only data
ALTER TABLE state_probate_rules ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can read state probate rules"
  ON state_probate_rules FOR SELECT
  TO anon, authenticated
  USING (true);

-- checklist_templates: public read-only data
ALTER TABLE checklist_templates ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can read checklist templates"
  ON checklist_templates FOR SELECT
  TO anon, authenticated
  USING (true);

-- subscription_templates: public read-only data
ALTER TABLE subscription_templates ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can read subscription templates"
  ON subscription_templates FOR SELECT
  TO anon, authenticated
  USING (true);

-- cases: authenticated users manage their own cases
ALTER TABLE cases ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read their own cases"
  ON cases FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "Users can create cases"
  ON cases FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own cases"
  ON cases FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own cases"
  ON cases FOR DELETE
  TO authenticated
  USING (auth.uid() = user_id);

-- case_checklist_items: access via case ownership
ALTER TABLE case_checklist_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read their own checklist items"
  ON case_checklist_items FOR SELECT
  TO authenticated
  USING (EXISTS (
    SELECT 1 FROM cases WHERE cases.id = case_checklist_items.case_id AND cases.user_id = auth.uid()
  ));

CREATE POLICY "Users can create checklist items for their cases"
  ON case_checklist_items FOR INSERT
  TO authenticated
  WITH CHECK (EXISTS (
    SELECT 1 FROM cases WHERE cases.id = case_checklist_items.case_id AND cases.user_id = auth.uid()
  ));

CREATE POLICY "Users can update their own checklist items"
  ON case_checklist_items FOR UPDATE
  TO authenticated
  USING (EXISTS (
    SELECT 1 FROM cases WHERE cases.id = case_checklist_items.case_id AND cases.user_id = auth.uid()
  ))
  WITH CHECK (EXISTS (
    SELECT 1 FROM cases WHERE cases.id = case_checklist_items.case_id AND cases.user_id = auth.uid()
  ));

CREATE POLICY "Users can delete their own checklist items"
  ON case_checklist_items FOR DELETE
  TO authenticated
  USING (EXISTS (
    SELECT 1 FROM cases WHERE cases.id = case_checklist_items.case_id AND cases.user_id = auth.uid()
  ));

-- generated_documents: access via case ownership
ALTER TABLE generated_documents ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read their own generated documents"
  ON generated_documents FOR SELECT
  TO authenticated
  USING (EXISTS (
    SELECT 1 FROM cases WHERE cases.id = generated_documents.case_id AND cases.user_id = auth.uid()
  ));

CREATE POLICY "Users can create documents for their cases"
  ON generated_documents FOR INSERT
  TO authenticated
  WITH CHECK (EXISTS (
    SELECT 1 FROM cases WHERE cases.id = generated_documents.case_id AND cases.user_id = auth.uid()
  ));

-- affiliate_partners: public read-only data
ALTER TABLE affiliate_partners ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can read affiliate partners"
  ON affiliate_partners FOR SELECT
  TO anon, authenticated
  USING (true);

-- affiliate_clicks: anyone can insert (tracking), no read for anon
ALTER TABLE affiliate_clicks ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can create affiliate clicks"
  ON affiliate_clicks FOR INSERT
  TO anon, authenticated
  WITH CHECK (true);

CREATE POLICY "Users can read their own affiliate clicks"
  ON affiliate_clicks FOR SELECT
  TO authenticated
  USING (EXISTS (
    SELECT 1 FROM cases WHERE cases.id = affiliate_clicks.case_id AND cases.user_id = auth.uid()
  ));

-- deadline_reminders: access via case ownership
ALTER TABLE deadline_reminders ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read their own deadline reminders"
  ON deadline_reminders FOR SELECT
  TO authenticated
  USING (EXISTS (
    SELECT 1 FROM cases WHERE cases.id = deadline_reminders.case_id AND cases.user_id = auth.uid()
  ));

CREATE POLICY "Users can create reminders for their cases"
  ON deadline_reminders FOR INSERT
  TO authenticated
  WITH CHECK (EXISTS (
    SELECT 1 FROM cases WHERE cases.id = deadline_reminders.case_id AND cases.user_id = auth.uid()
  ));

CREATE POLICY "Users can update their own reminders"
  ON deadline_reminders FOR UPDATE
  TO authenticated
  USING (EXISTS (
    SELECT 1 FROM cases WHERE cases.id = deadline_reminders.case_id AND cases.user_id = auth.uid()
  ))
  WITH CHECK (EXISTS (
    SELECT 1 FROM cases WHERE cases.id = deadline_reminders.case_id AND cases.user_id = auth.uid()
  ));

CREATE POLICY "Users can delete their own reminders"
  ON deadline_reminders FOR DELETE
  TO authenticated
  USING (EXISTS (
    SELECT 1 FROM cases WHERE cases.id = deadline_reminders.case_id AND cases.user_id = auth.uid()
  ));
